[package]
authors = ["Arvid Norlander"]
categories = ["config"]
description = "Chezmoi addon to patch ini files with mixed settings and state (experimental rust branch)"
edition = "2021"
keywords = ["ini", "config", "configuration", "chezmoi"]
license = "GPL-3.0-only"
name = "chezmoi_modify_manager"
repository = "https://github.com/VorpalBlade/chezmoi_modify_manager"
rust-version = "1.70.0"
version = "2.2.3"

[features]
default = ["updater-tls-rusttls"]
# Built in updater, distro packages probably wants to disable this.
# This is the version based on native TLS: platform OpenSSL or platform specific
updater-tls-native = ["self_update", "reqwest", "reqwest/default-tls"]
# Built in updater, distro packages probably wants to disable this.
# This is the version based on vendored OpenSSL
updater-tls-native-vendored = [
    "self_update",
    "reqwest",
    "reqwest/native-tls-vendored",
]
# Built in updater, distro packages probably wants to disable this.
# This is the version based on RustTLS: TLS entirely in rust.
updater-tls-rusttls = ["self_update", "self_update/rustls"]

[target.'cfg(windows)'.dependencies]
self_update = { version = "0.39.0", optional = true, default-features = false, features = [
    "archive-zip",
    "compression-zip-deflate",
] }

[target.'cfg(unix)'.dependencies]
self_update = { version = "0.39.0", optional = true, default-features = false, features = [
    "archive-tar",
    "compression-flate2",
] }

[dependencies]
anstream = "0.6.5"
anstyle = "1.0.4"
anyhow = { version = "1.0.76", features = ["backtrace"] }
bpaf = { version = "0.9", features = ["autocomplete", "derive"] }
camino = "1.1.6"
duct = "0.13.7"
env_logger = { version = "0.10.1", default-features = false }
glob = "0.3.1"
indoc = "2.0.4"
ini-merge = { version = "0.3.4", default-features = false, features = [
    "keyring",
] }
itertools = "0.12.0"
log = "0.4.20"
os_info = { version = "3.7.0", default-features = false }
reqwest = { version = "0.11", default-features = false, optional = true }
rustc_version_runtime = "0.3.0"
strum = { version = "0.25.0", features = ["derive"] }
which = { version = "5.0.0", default-features = false }
winnow = "0.5.30"

[dev-dependencies]
pathdiff = { version = "0.2.1", features = ["camino"] }
pretty_assertions = "1.4.0"
tempfile = "3.8.1"

[profile.dev]
# Disabling debug info speeds up builds a bunch,
# and we don't rely on it for debugging that much.
debug = 0
