[package]
authors = ["Arvid Norlander"]
categories = ["config"]
description = "Chezmoi addon to patch ini files with mixed settings and state (experimental rust branch)"
edition = "2021"
keywords = ["ini", "config", "configuration", "chezmoi"]
license = "GPL-3.0-only"
name = "chezmoi_modify_manager"
repository = "https://github.com/VorpalBlade/chezmoi_modify_manager"
version = "2.0.4"

[features]
default = ["updater", "updater-tls-rusttls"]
# Built in updater, distro packages probably wants to disable this
updater = ["self_update"]
# Use native TLS
updater-tls-native = ["updater", "reqwest", "reqwest/default-tls"]
# Use vendored native TLS
updater-tls-native-vendored = [
    "updater",
    "reqwest",
    "reqwest/native-tls-vendored",
]
# Use rusttls instead of native TLS
updater-tls-rusttls = ["updater", "self_update/rustls"]

[target.'cfg(windows)'.dependencies]
self_update = { version = "0.36.0", optional = true, default-features = false, features = [
    "archive-zip",
    "compression-zip-deflate",
] }

[target.'cfg(unix)'.dependencies]
self_update = { version = "0.36.0", optional = true, default-features = false, features = [
    "archive-tar",
    "compression-flate2",
] }

[dependencies]
anyhow = { version = "1.0.70", features = ["backtrace"] }
bpaf = { version = "0.8", features = ["autocomplete", "derive"] }
duct = "0.13.6"
indoc = "2.0.1"
ini-merge = { version = "0.1.0", default-features = false, features = [
    "keyring",
] }
itertools = "0.10.5"
reqwest = { version = "0.11", default-features = false, optional = true }
strum = { version = "0.24.1", features = ["derive"] }
thiserror = "1.0.40"
winnow = "0.4.1"

[dev-dependencies]
pretty_assertions = "1.3.0"
