name: Continuous integration

permissions:
  contents: read

on:
  push:
    branches: [ "v2" ]
  pull_request:
    branches: [ "v2" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test - ${{ matrix.target }} with rust ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - i686-unknown-linux-gnu
          - riscv64gc-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Install cross
        uses: taiki-e/install-action@cross
      - name: Cross compile and test
        run: cross test --target ${{ matrix.target }} --verbose
